# Changes here will be overwritten by Copier
_commit: c43da8a
_src_path: ../nialov-py-template/
classifier: 'Topic :: Scientific/Engineering :: GIS'
description: Switch between spatial fileformats.
email: nikolasovaskainen@gmail.com
full_name: Nikolas Ovaskainen
github_account: nialov
keywords: data spatial
package: geotrans
year: 2020
