from setuptools import setup, find_packages

with open("README.md", "r") as fh:
    long_description = fh.read()

setup(
    extras_require={
        "dev": [
            "alabaster==0.7.12",
            "appdirs==1.4.4",
            "attrs==19.3.0",
            "babel==2.8.0",
            "black==19.10b0; python_version >= '3.6'",
            "cached-property==1.5.1",
            "cerberus==1.3.2",
            "certifi==2020.6.20",
            "chardet==3.0.4",
            "click==7.1.2",
            "click-plugins==1.1.1",
            "cligj==0.5.0",
            "colorama==0.4.3",
            "commonmark==0.9.1",
            "distlib==0.3.1",
            "docutils==0.16",
            "filelock==3.0.12",
            "fiona==1.8.13.post1",
            "geopandas==0.8.0",
            "hypothesis==5.19.0",
            "idna==2.10",
            "imagesize==1.2.0",
            "jinja2==2.11.2",
            "markupsafe==1.1.1",
            "more-itertools==8.4.0",
            "munch==2.5.0",
            "numpy==1.19.0",
            "orderedmultidict==1.0.1",
            "packaging==20.4",
            "pandas==1.0.5",
            "pathspec==0.8.0",
            "pep517==0.8.2",
            "pip-shims==0.5.2",
            "pipenv-setup==3.1.1",
            "pipfile==0.0.2",
            "plette[validation]==0.2.3",
            "pluggy==0.13.1",
            "py==1.9.0",
            "pygments==2.6.1",
            "pyparsing==2.4.7",
            "pyproj==2.6.1.post1",
            "pytest==5.4.3",
            "python-dateutil==2.8.1",
            "pytz==2020.1",
            "recommonmark==0.6.0",
            "regex==2020.6.8",
            "requests==2.24.0",
            "requirementslib==1.5.12",
            "shapely==1.7.0",
            "six==1.15.0",
            "snowballstemmer==2.0.0",
            "sortedcontainers==2.2.2",
            "sphinx==3.1.2",
            "sphinxcontrib-applehelp==1.0.2",
            "sphinxcontrib-devhelp==1.0.2",
            "sphinxcontrib-htmlhelp==1.0.3",
            "sphinxcontrib-jsmath==1.0.1",
            "sphinxcontrib-qthelp==1.0.3",
            "sphinxcontrib-serializinghtml==1.1.4",
            "toml==0.10.1",
            "tomlkit==0.6.0",
            "tox==3.16.1",
            "typed-ast==1.4.1",
            "urllib3==1.25.9",
            "virtualenv==20.0.26",
            "vistir==0.5.2",
            "wcwidth==0.2.5",
            "wheel==0.34.2",
        ]
    },
    name="geotrans",
    version="0.1",
    author="Nikolas Ovaskainen",
    author_email="nikolasovaskainen@gmail.com",
    description="Fast geodata filetype transformations using geopandas.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    packages=find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    include_package_data=True,
    install_requires=[
        "attrs==19.3.0",
        "click==7.1.2",
        "click-plugins==1.1.1",
        "cligj==0.5.0",
        "fiona==1.8.13.post1",
        "geopandas==0.8.0",
        "munch==2.5.0",
        "numpy==1.19.0",
        "pandas==1.0.5",
        "pyproj==2.6.1.post1",
        "python-dateutil==2.8.1",
        "pytz==2020.1",
        "shapely==1.7.0",
        "six==1.15.0",
    ],
    test_require=["pytest", "sphinx", "recommonmark"],
    dependency_links=[],
    python_requires=">=3.7",
    entry_points="""
        [console_scripts]
        geotrans=geotrans.cli:main
    """,
)
